# Generated by Django 2.0.6 on 2018-08-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.FileField(default='https://img.theweek.in/content/dam/week/leisure/society/images/2018/3/17/tom-and-jerry.jpg', upload_to=''),
        ),
    ]
