# Generated by Django 2.0.6 on 2018-08-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
