# Generated by Django 2.0.6 on 2018-08-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_auto_20180820_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.EmailField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='common.User')),
                ('passout_year', models.DateField(blank=True, null=True)),
                ('current_address', models.TextField(blank=True, max_length=500, null=True)),
                ('permanent_address', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='about.Profile')),
                ('institution', models.CharField(max_length=80)),
                ('course', models.CharField(choices=[('X', 'Secondary'), ('XII', 'Higher Secondary'), ('BTech', 'Bachelor of Technology'), ('MTech', 'Master of Technology'), ('Phd', 'Doctorate')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='about.Profile')),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('time_period', models.CharField(max_length=50)),
                ('comments', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='telegram',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Profile'),
        ),
        migrations.AddField(
            model_name='phone',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Profile'),
        ),
        migrations.AddField(
            model_name='email',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Profile'),
        ),
    ]
